on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@4

      - name: Set up Node
        uses: actions/setup-node@4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build
